```{r}
library(ggplot2)
library(tidyr)
library(knitr)
library(MASS)
library(dplyr)
library(mvtnorm)
library(mice)
library(ROCR)
source("saem_model_selection_fct2.R")
```

```{r}
#-------------------Load dataset---------------------- 
traumdata <- read.csv(file="trauma.csv",sep=',', header = TRUE,na.strings = c("","NR","IMP","NA","NF"),encoding = "UTF-8",
                      row.names=1)
SAMU <- traumdata[ ,c(10:14,225:228,234,33:35,15,18,229:233,244,19:30,41:42,49:54,48,58,61,44,46:47,55:57,60,62, 38)]
criteria = read.csv('hemo_criteria.csv', header=T)

write.csv(SAMU, "SAMU.csv")
#summary(SAMU)
names(SAMU)
SAMU$BMI[3302]=SAMU$Poids[3302]/(SAMU$Taille[3302]^2)
SAMU=SAMU[-which(SAMU$ACR.1==1),]
Choc.hemorragique= traumdata$Choc.hemorragique
Choc.hemorragique = Choc.hemorragique[-which(traumdata$ACR.1==1)]
criteria = criteria[-which(traumdata$ACR.1==1),]

Choc.hemorragique = Choc.hemorragique[-which(SAMU$Mecanisme=="Arme blanche" | SAMU$Mecanisme=="Arme à feu")]
criteria = criteria[-which(SAMU$Mecanisme=="Arme blanche" | SAMU$Mecanisme=="Arme à feu"),]
SAMU=SAMU[-which(SAMU$Mecanisme=="Arme blanche" | SAMU$Mecanisme=="Arme à feu"),]

all(criteria$c3==Choc.hemorragique)
```


```{r}
#-------------------Select continues variables---------------------- 
SAMU_CONT = SAMU[,c(1,3:5,34:41,43:44,48:50)]
indx <- sapply(SAMU_CONT, is.factor)
SAMU_CONT[indx] <- lapply(SAMU_CONT[indx], function(x) as.numeric(as.character(x)))
which((SAMU_CONT$BMI>=SAMU_CONT$Poids/(SAMU_CONT$Taille^2)-0.1)&(SAMU_CONT$BMI<=SAMU_CONT$Poids/(SAMU_CONT$Taille^2)+0.1)==FALSE)

SAMU_CONT$SD.min=SAMU_CONT$PAS.min-SAMU_CONT$PAD.min
SAMU_CONT$SD.SMUR=SAMU_CONT$PAS.SMUR-SAMU_CONT$PAD.SMUR
SAMU_NEW = SAMU_CONT[,-c(7:8,10:11,15)]

p <- ggplot(data=SAMU_NEW)
for (n in names(SAMU_NEW)){
  print(p + geom_density(aes_string(x=n),alpha=.2, fill="#FF6666"))
}
```

```{r}
#------------------model selection-------------
best.subsets = list()
bics = list()
aics = list()

for(crit in c(2,1,3,4)){
  print(paste('Evaluating criterion', names(criteria[crit])))
  Choc.hemorragique = criteria[,crit]
  
  set.seed(100) # Set Seed so that same sample can be reproduced in future also
  # Now Selecting 80% of data as sample from total 'n' rows of the data  
  #sample <- sample.int(n = nrow(SAMU_NEW), size = floor(.2*nrow(SAMU_NEW)), replace = F)
  sample =1:1277
  SAMU.train  <- SAMU_NEW[-sample, ]
  SAMU.test  <- SAMU_NEW[sample, ]
  
  Choc.hemorragique.train=Choc.hemorragique[-sample]
  Choc.hemorragique.test=Choc.hemorragique[sample]
  N=dim(SAMU.train)[1]
  p=dim(SAMU.train)[2]
  combinations = function(n){
    comb = NULL
    for( i in 1:n) comb = rbind(cbind(1,comb),cbind(0,comb))
    return(comb)
  }
  
  subsets=combinations(p)
  ll = ll1 = ll2 = matrix(-Inf,nrow=p,ncol=p)
  
  subsets1 = subsets[rowSums(subsets)==1,]
  for (j in 1:(nrow(subsets1))){
    cat('subset ',subsets1[j,],'\n')  
    pos_var=which(subsets1[j,]==1)
    list.saem.subset=miss.saem(data.matrix(SAMU.train),pos_var,Choc.hemorragique.train,maxruns=1000,tol_em=1e-7,nmcmc=2,print_iter=FALSE,ll_obs_cal=TRUE)
    ll[1,j] = list.saem.subset$ll
    ll1[1,j] = list.saem.subset$ll1
    ll2[1,j] = list.saem.subset$ll2
  }
  
  id = AIC = BIC = AIC1 = BIC1 = rep(0,p)
  subsetsi=subsets1
  SUBSETS = matrix(-Inf,nrow=p,ncol=p)
  for(i in 2:p){
    nb.x = i-1
    nb.para = (nb.x + 1) + p + p*p 
    id[i-1] = d = which.max(ll[i-1,])
    pos_var=which(subsetsi[d,]==1)
    AIC[i-1] =  -2*ll[i-1,d]+ 2*nb.para
    AIC1[i-1] = -2*ll1[i-1,d]+ 2*(nb.x+1)
    BIC[i-1] = -2*ll[i-1,d]+ nb.para * log(N)
    BIC1[i-1] = -2*ll1[i-1,d]+ (nb.x+1) * log(N)
    SUBSETS[i-1,]=subsetsi[d,]
    if(i==2){subsetsi = subsets[(rowSums(subsets)==i) & (subsets[,pos_var]==i-1),]}
    if(i>2){ subsetsi = subsets[(rowSums(subsets)==i) & (rowSums(subsets[,pos_var])==i-1),]}
    if(!is.matrix(subsetsi)){subsetsi = t(as.matrix(subsetsi))}
    subsetsi = as.matrix(subsetsi)
    for (j in 1:(nrow(subsetsi))){
      cat('subset ',subsetsi[j,],'\n')  
      pos_var=which(subsetsi[j,]==1)
      list.saem.subset=miss.saem(data.matrix(SAMU.train),pos_var,Choc.hemorragique.train,maxruns=1000,tol_em=1e-7,nmcmc=2,print_iter=FALSE,ll_obs_cal=TRUE)
      ll[i,j] = list.saem.subset$ll
      ll1[i,j] = list.saem.subset$ll1
      ll2[i,j] = list.saem.subset$ll2
    }
  }
  
  list.saem.subset=miss.saem(data.matrix(SAMU.train),1:p,Choc.hemorragique.train,maxruns=1000,tol_em=1e-7,nmcmc=2,print_iter=FALSE,ll_obs_cal=TRUE)
  ll[p,1] = list.saem.subset$ll
  ll1[p,1] = list.saem.subset$ll1
  ll2[p,1] = list.saem.subset$ll2
  nb.x = p
  nb.para = (nb.x + 1) + p + p*p 
  AIC[p] =  -2*ll[p,1]+ 2*nb.para 
  AIC1[p] = -2*ll1[p,1]+ 2*(nb.x+1)#11
  BIC[p] = -2*ll[p,1]+ nb.para * log(N)
  BIC1[p] = -2*ll1[p,1]+ (nb.x+1) * log(N)
  
  #par(mfrow=c(2,2))
  #plot(AIC)
  #plot(BIC)
  #plot(AIC1)
  #plot(BIC1)
  
  best.subseti = names(SAMU.train)[SUBSETS[which.min(BIC),]==1]
  print(best.subseti)
  best.subsets[[names(criteria[crit])]] = best.subseti
  bics[[names(criteria[crit])]] = BIC
  aics[[names(criteria[crit])]] = AIC
}
```
```{r}
print(best.subsets)
bicsdf = data.frame(bics)
bicsdf = bicsdf %>% sapply(function(x) scale(x,scale = T)) %>% as.data.frame()
bicsdf$n.variables = 1:p
bics.plot = bicsdf %>% gather('Criterion', 'BIC', -n.variables) %>%
  ggplot() + aes(x=n.variables, y=BIC, color=Criterion) + geom_line()
bics.plot
```
```{r}
order.variables = list()
order.variables[['c3']] = c(7, 9, 12, 11, 13, 6, 14, 1)
order.variables[['c5']] = c(13, 8, 9, 12, 11, 1, 14, 10)
order.variables[['c4']] = c(12, 9, 7, 11, 5, 13, 1, 14)
order.variables[['c1']] = c(7, 12, 9, 11, 13, 5, 3, 14)

best.subset.ordered = list()
for(n in names(order.variables)){
  best.subset.ordered[[n]] = colnames(SAMU.train[order.variables[[n]]])
}
```


```{r}
criteria.comparison.results = list(best.subsets=best.subsets, best.subset.ordered=best.subset.ordered, aics=aics, bics=bics, bics.plot=bics.plot)
save(criteria.comparison.results, file='criteria.comparison.results.RData')
```

