---
title: "EDA"
output: html_document
---
```{r, results="hide", message=FALSE}
## Imports
library(tidyverse)
library(verification)
library(pander)
library(Amelia)
library(gridExtra)
library(grid)
library(GGally)
library(plotrix)

# Custom imports
aux.folder = '../auxiliary/'
source(paste(aux.folder,'dataloaders.R',sep=''), chdir = T)
data_folder = '../../Data/'

themer = function(sizeAxis = 10, sizeAxisTitle=13,
                  sizeLegend=15, sizeStrip = 15, angle=T, boldX=F){
  if(angle){
    a=45
    h=1
  }
  else{
    a=0
    h=0.5
  }
  if(boldX){
    xface = 'bold'
  }
  else{
    xface=NULL
  }
  return(
    theme(axis.text.y= element_text(size=sizeAxis),
          axis.text.x=element_text(size=sizeAxis,
                                   angle=a, hjust=h, face=xface),
          axis.title = element_text(size=sizeAxisTitle),
          legend.text=element_text(size=sizeLegend),
          legend.title=element_text(size=sizeLegend,
                                    face='bold'),
          strip.text.x = element_text(size=sizeStrip,
                                      face='bold')
          )
  )
}

color2D.matplot.abs = function (x, cs1 = c(0, 1), cs2 = c(0, 1), cs3 = c(0, 1), extremes = NA, 
    cellcolors = NA, show.legend = FALSE, nslices = 10, xlab = "Column", 
    ylab = "Row", do.hex = FALSE, axes = TRUE, show.values = FALSE, 
    vcol = NA, vcex = 1, border = "black", na.color = NA, xrange = NULL, 
    color.spec = "rgb", yrev = TRUE, xat = NULL, yat = NULL, 
    Hinton = FALSE, ...) 
{
    if (diff(range(x, na.rm = TRUE)) == 0) 
        x <- x/max(x, na.rm = TRUE)
    if (is.matrix(x) || is.data.frame(x)) {
        xdim <- dim(x)
        if (is.data.frame(x)) 
            x <- unlist(x)
        else x <- as.vector(x)
        oldpar <- par("xaxs", "yaxs", "xpd", "mar")
        par(xaxs = "i", yaxs = "i")
        if (do.hex) 
            par(mar = c(5, 4, 4, 4))
        plot(c(0, xdim[2]), c(0, xdim[1]), xlab = xlab, ylab = ylab, 
            type = "n", axes = FALSE, ...)
        oldpar$usr <- par("usr")
        if (!do.hex) {
            box()
            pos <- 0
        }
        else pos <- -0.3
        if (axes) {
            if (is.null(xat)) 
                xat <- pretty(0:xdim[2])[-1]
            axis(1, at = xat - 0.5, labels = xat, pos = pos)
            if (is.null(yat)) 
                yat <- pretty(0:xdim[1])[-1]
            axis(2, at = xdim[1] - yat + 0.5, labels = yat)
        }
        if (all(is.na(cellcolors))) {
            if (Hinton) {
                if (is.na(extremes[1])) 
                  extremes <- c("black", "white")
                cellcolors <- extremes[(x > 0) + 1]
            }
            else cellcolors <- color.scale(abs(x), cs1, cs2, cs3, 
                extremes = extremes, na.color = na.color, color.spec = color.spec)
        }
        if (is.na(vcol)) 
            vcol <- ifelse(colSums(col2rgb(cellcolors) * c(1, 
                1.4, 0.6)) < 350, "white", "black")
        if (Hinton) {
            if (any(x < 0 | x > 1)) 
                cellsize <- matrix(rescale(abs(x), c(0, 1)), 
                  nrow = xdim[1])
        }
        else cellsize <- matrix(1, nrow = xdim[1], ncol = xdim[2])
        if (do.hex) {
            par(xpd = TRUE)
            offset <- 0
            if (length(border) < xdim[1] * xdim[2]) 
                border <- rep(border, length.out = xdim[1] * 
                  xdim[2])
            for (row in 1:xdim[1]) {
                for (column in 0:(xdim[2] - 1)) {
                  hexagon(column + offset, xdim[1] - row, unitcell = cellsize[row, 
                    column + 1], col = cellcolors[row + xdim[1] * 
                    column], border = border[row + xdim[1] * 
                    column])
                  if (show.values) 
                    text(column + offset + 0.5, xdim[1] - row + 
                      0.5, x[row + column * xdim[1]], col = vcol[row + 
                      xdim[1] * column], cex = vcex)
                }
                offset <- ifelse(offset, 0, 0.5)
            }
            par(xpd = FALSE)
        }
        else {
            if (Hinton) 
                inset <- (1 - cellsize)/2
            else inset <- 0
            if (yrev) {
                y0 <- rep(seq(xdim[1] - 1, 0, by = -1), xdim[2]) + 
                  inset
                y1 <- rep(seq(xdim[1], 1, by = -1), xdim[2]) - 
                  inset
            }
            else {
                y0 <- rep(0:(xdim[1] - 1), xdim[2]) + inset
                y1 <- rep(1:xdim[1], xdim[2]) - inset
            }
            rect(sort(rep((1:xdim[2]) - 1, xdim[1])) + inset, 
                y0, sort(rep(1:xdim[2], xdim[1])) - inset, y1, 
                col = cellcolors, border = border)
            if (show.values) {
                if (yrev) 
                  texty <- rep(seq(xdim[1] - 0.5, 0, by = -1), 
                    xdim[2])
                else texty <- rep(seq(0.5, xdim[1] - 0.5, by = 1), 
                  xdim[2])
                text(sort(rep((1:xdim[2]) - 0.5, xdim[1])), texty, 
                  formatC(round(x, show.values), format = "f", 
                    digits = show.values), col = vcol, cex = vcex)
            }
        }
        naxs <- which(is.na(x))
        xy <- par("usr")
        plot.din <- par("din")
        plot.pin <- par("pin")
        bottom.gap <- (xy[3] - xy[4]) * (plot.din[2] - plot.pin[2])/(2 * 
            plot.pin[2])
        grx1 <- xy[1]
        gry1 <- bottom.gap * 0.95
        grx2 <- xy[1] + (xy[2] - xy[1])/4
        gry2 <- bottom.gap * 0.8
        if (length(cellcolors) > 1) {
            colmat <- col2rgb(c(cellcolors[which.min(x)], cellcolors[which.max(x)]))
            cs1 <- colmat[1, ]/255
            cs2 <- colmat[2, ]/255
            cs3 <- colmat[3, ]/255
            color.spec <- "rgb"
        }
        rect.col <- color.scale(1:nslices, cs1, cs2, cs3, color.spec = color.spec)
        if (show.legend) 
            color.legend(grx1, gry1, grx2, gry2, round(range(x, 
                na.rm = TRUE), show.legend), rect.col = rect.col)
        par(oldpar)
    }
    else cat("x must be a data frame or matrix\n")
}
```

```{r}
trauma = loader('trauma')
X = cbind(trauma$X_numeric, trauma$X_category$Sexe)
colnames(X)[ncol(X)] = 'Sexe'
y = trauma$y
y=factor(c('No shock','Sock')[as.numeric(y)])

X = X[c('Sexe', "Age", "BMI","Glasgow.initial", 'FC.max', "SD.min", "Hemocue.init", "SpO2.min", "Remplissage.total.cristalloides", 
"Remplissage.total.colloides")]
colnames(X) = c('Sex', 'Age', "BMI", 'Glasgow', 'Heart.rate', 'Pulse.pressure', 'Hb.level', 'O2.saturation', 'Cristalloids.IV', 'Colloids.IV')

X$Expander = X$Cristalloids.IV + X$Colloids.IV
X$Colloids.IV = NULL
X$Cristalloids.IV = NULL

dat = cbind(X,y)
```

```{r}
colMeans(is.na(X))*100
```

```{r}
colSums(is.na(X))
```

```{r}
summary(dat)
```

```{r}
missmap(X, margins = c(5,1), y.labels = rep('',nrow(X)), rank.order=F)
```

```{r}
ggplot(dat) + aes(x=Glasgow, fill=y) + geom_bar(position='dodge', aes(y =..prop..)) + 
  themer(angle=F) + scale_fill_manual(labels = c("No shock", "Shock"), values=c('darkblue', 'red')) +
  xlab('GCS score') + ylab('Proportion of occurences') + 
  scale_x_continuous(breaks=3:15) + labs(fill='Outcome')
```

```{r}
ggplot(dat) + aes(x=Expander, fill=y) + geom_histogram(position='dodge', aes(y=..density..), bins=15) + 
  themer(angle=F) + scale_fill_manual(labels = c("No shock", "Shock"), values=c('darkblue', 'red')) +
  xlab('Volume Expander injection') + ylab('Density')
```

```{r}
#ggpairs(dat, progress=F)
```

```{r}
dat %>% gather('variable','value', c('Age','BMI','Heart.rate','Pulse.pressure', 'Hb.level', 'O2.saturation', 'Expander')) %>%
  ggplot() + aes(x=value, fill=y) + geom_histogram(aes(y=..density..), bins=30) + facet_wrap(~variable, scales = 'free') + themer() + xlab('') + ylab('') +
  labs(fill = "Outcome") + theme(axis.text.y = element_blank(), axis.ticks.y = element_blank())
```

```{r}
par(mar=c(1,7,1,1),xaxt='n',yaxt='n')
grid = 1:(ncol(X)-1)
tlab = 0.5:(length(grid)-0.5)
lab = colnames(X)[-1]
cor(is.na(X[,-1])) %>% as.data.frame() %>% color2D.matplot.abs(show.values=2, axes=F, xlab='', ylab='')
axis(1, at=tlab, labels=F)
#text(x=tlab, y=par()$usr[3]-0.1*(par()$usr[4]-par()$usr[3]), 
 #    labels=lab, srt=45, adj=1, xpd=T)
axis(2, at=tlab, labels=F)
text(y=tlab, x=par()$usr[1] -0.02*(par()$usr[2]-par()$usr[1]), 
     labels=rev(lab), srt=0, adj=1, xpd=T)
#title('Correlation between the missingness of variables')
```
```{r}
y.bk = dat$y
sex.bk = dat$Sex
dat$Shock = as.numeric(dat$y)
dat$Sex = as.numeric(dat$Sex)
dat$y=NULL

par(mar=c(1,7,1,1), xaxt='n',yaxt='n')
grid = 1:(ncol(dat))
tlab = 0.5:(length(grid)-0.5)
lab = colnames(dat)
cor(dat, use='complete.obs') %>% as.data.frame() %>%color2D.matplot.abs(show.values=2, axes=F, xlab='', ylab='')
axis(1, at=tlab, labels=F)
#text(x=tlab, y=par()$usr[3]-0.1*(par()$usr[4]-par()$usr[3]), 
#     labels=lab, srt=45, adj=1, xpd=T)
axis(2, at=tlab, labels=F)
text(y=tlab, x=par()$usr[1] -0.02*(par()$usr[2]-par()$usr[1]), 
     labels=rev(lab), srt=0, adj=1, xpd=T)
#title('Correlation between measurements\n(based on complete cases)')

dat$Shock = NULL
dat$y = y.bk
dat$Sex = sex.bk
```


```{r}
y.bk = dat$y
sex.bk = dat$Sex
dat$Shock = as.numeric(dat$y)
dat$Sex = as.numeric(dat$Sex)
dat$y=NULL
print('Correlation between missingness of covariates and Hemo shock')
cor(cbind(is.na(dat[,-c(1,10)]), dat$Shock)) %>% as.data.frame() %>% dplyr::select(9) %>% rename(Shock=V9)

dat$Shock = NULL
dat$y = y.bk
dat$Sex = sex.bk
```

```{r}
ggplot() + aes(x=rowSums(is.na(X))) + geom_bar() + themer(angle=F) + ylab('Number of occurences') + xlab('Number of missing values')
```

