---
title: "Point vs draw"
output: html_document
---
```{r setup, include=FALSE}
library(tidyverse)
library(MLmetrics)
```

```{r}
aux.folder = '../auxiliary/'
source(paste(aux.folder,'MVN_imputation.R',sep=''), chdir = T)
source(paste(aux.folder,'generate_missing.R',sep=''), chdir = T)
source(paste(aux.folder,'prediction_methods.R',sep=''), chdir = T)
source(paste(aux.folder,'simulation_methods.R',sep=''), chdir = T)
data_folder = '../../Data/'
dataset = 'abalone'


seed = ceiling(runif(1,1e3,1e5))
print(seed)
seed.run = 124
``` 

```{r}
rowMedians = function(X){
  return(apply(X,1,median))
}

lm.predVar = function(X.new, X.fit, fittedM){
  sigma2 = (summary(fittedM)$sigma)**2
  print(sigma2)
  inv.cov = solve(t(X.fit) %*% X.fit)
  z = X.new %*% inv.cov
  res = rowSums(X.new*z)
  print(res)
  return(res * sigma2)
}

```
```{r}
oneRun = function(args){
  for(name in names(args)){
    assign(name, args[[name]])
  }
  if(exists('seed.run')){
    set.seed(seed.run)
    print('seeded')
    print(seed.run)
  }
  X = X.gen(args)
  y.g = y.gen(X,args)
  
  y = y.g$y
  X = y.g$X
  

  
  spl = train_test_split(X, y, train_prop)
  X.train = spl$X.train
  X.test = spl$X.test
  y.train = spl$y.train
  y.test = spl$y.test
  
  X.train = MCAR.noEmptyLines(X.train, miss_prop)
  X.test = MCAR.noEmptyLines(X.test, miss_prop)
  
  pre.train = prelim.norm2(X.train) 
  pre.test = prelim.norm2(X.test)
  imp.train = em.norm(pre.train)
  
  
  X.train.single.imp = imp.mvnorm.estim(list(thetahat=imp.train,params=getparam.norm(pre.train,imp.train)),X.train)
  X.test.single.imp = imp.mvnorm.estim(list(thetahat=imp.train,params=getparam.norm(pre.train,imp.train)),X.test)
  
    print(head(X.test.single.imp))
  

  datasets.train = list()
  datasets.test = list()
  for(i in 1:m){
    datasets.train[[i]] = imp.norm(pre.train,imp.train,X.train)
    datasets.test[[i]] = imp.norm(pre.test, imp.train, X.test)
  }
  
  single.imp.fit = (predictor$train)(X.train.single.imp, y.train)
  MI.regressors.fit = lapply(1:m,
                          function(i) {(predictor$train)(datasets.train[[i]], y.train)})
  predictions = list()
  predictions.MI = lapply(1:m, function(i){(predictor$predict)(MI.regressors.fit[[i]], datasets.test[[i]])}) %>% as.data.frame()
  predictions$MI = predictions.MI %>% rowMeans() #rowMedians() #
  predictions$SI = (predictor$predict)(single.imp.fit, X.test.single.imp)
  
  MI.var_b = apply(predictions.MI,1,var)
  MI.var_w = lapply(1:m, function(i) lm.predVar(datasets.test[[i]], datasets.train[[i]], MI.regressors.fit[[i]])) %>% as.data.frame() %>% rowMeans()
  MI.var_tot = MI.var_w + (1 + 1/m) * MI.var_b * 2
  MI.df = (m-1) * (1 + MI.var_w / ((1+1/m)*MI.var_b))**2
  MI.quantiles = t(sapply(MI.df, function(x) qt(c(alpha/2,1-alpha/2), df=x))) * sqrt(MI.var_tot) + rowMeans(predictions.MI)
  coverage = mean(y.test > MI.quantiles[,1] & y.test < MI.quantiles[,2])
  
  res = lapply(predictions, function(x) mean((x-y.test)^2))
  res$Coverage = coverage
  res$varW = mean(MI.var_w)
  res$varB = mean(MI.var_b)
  return(res)
}

```
```{r}
X.gen = X.basic.MVN
y.gen = y.regression
predictor = reg.lin
argsL = list(n=1000,
            p=5,
            rho=0.5,
            sigma_reg = 0.2,
            train_prop=0.6,
            miss_prop=0.4,
            alpha = 0.3,
            m=c(1:29,seq(30,200,20))
)

S = 1
res.1 = evaluate.S.run.multiArg(S,argsL, oneRun, do.parallel = T) 
```

```{r}
res.1 %>% gather('method','error', c(MI,SI)) %>%
  ggplot() + aes(x=m, y=error, color=method) + geom_line()
```
```{r}
res.1 %>%
  ggplot() + aes(x=m,y=Coverage) + geom_line() + geom_line(aes(y=1-alpha, color='Nominal coverage'))

res.1 %>%
  ggplot() + aes(x=m,y=varB) + geom_line() 
```

```{r}
X.gen = X.abalone
y.gen = y.abalone
predictor = reg.lin
argsL = list(n=1000,
            p=5,
            rho=0.5,
            sigma_reg = 0.2,
            train_prop=0.6,
            miss_prop=0.3,
            alpha = 0.3,
            m=c(1:29,seq(30,200,20))
)

S = 1
res.2 = evaluate.S.run.multiArg(S,argsL, oneRun, do.parallel = T) 
```

```{r}
res.2 %>% gather('method','error', c(MI,SI)) %>%
  ggplot() + aes(x=m, y=error, color=method) + geom_line()
```

```{r}
res.2 %>%
  ggplot() + aes(x=m,y=Coverage) + geom_line() + geom_line(aes(y=1-alpha, color='Nominal coverage'))

res.2 %>%
  ggplot() + aes(x=m,y=varB) + geom_line() 
```


