```{r}
library(tidyverse)
library(MASS)

aux.folder = '../../auxiliary/'
source(paste(aux.folder,'MVN_imputation.R',sep=''), chdir = T)
```

```{r}
train_prop = 0.7
miss_prop_test = 0.3
nLine = 4000

setwd('~/thesis_repo/Data/')
dat = read.csv('abalone.csv')
dat = dat[1:nLine,]

X = dat[c("LongestShell", "ShellWeight")]
y = dat$Rings

MCAR.noEmptyLines <- function(X, miss_prop.){
  n = nrow(X)
  m = ncol(X)
  missing = matrix(runif(n*m), nrow=n, ncol=m) <= miss_prop.
  missing[rowSums(missing)==ncol(X), 1] = F
  X[missing] = NA
  return(X)
}
```

```{r}
errs.true = c()
errs.miss = c()
errs.mvn = c()

miss.train.l = seq(0,0.8,0.005)
#miss.train.l = c(0.01)
for(miss_train in miss.train.l){
  set.seed(123)
  inTrain = sample(1:length(y), ceiling(train_prop*length(y)))
  X.train = X[inTrain,]
  X.test = X[-inTrain,]
  y.train = y[inTrain]
  y.test = y[-inTrain]
  X.test.true = X.test
  X.test = MCAR.noEmptyLines(X.test,miss_prop_test)
  X.train.miss = MCAR.noEmptyLines(X.train, miss_train)
  mu.true = colMeans(X.train)
  mu.miss = colMeans(X.train.miss, na.rm = T)

  X.test.filled.trueMean = X.test
  X.test.filled.missMean = X.test
  X.train.filled = X.train.miss
  imp.mvn.train = imp.mvnorm.train(X.train.miss)
  X.train.filledMVN = imp.mvnorm.estim(imp.mvn.train,X.train.miss)
  X.test.filledMVN = imp.mvnorm.estim(imp.mvn.train,X.test)

  for(i in 1:ncol(X)){
    miss.pos = is.na(X.test[,i])
    X.test.filled.trueMean[miss.pos,i] = mu.true[i]
    X.test.filled.missMean[miss.pos,i] = mu.miss[i]

    miss.pos = is.na(X.train.miss[,i])
    X.train.filled[miss.pos,i] = mu.miss[i]
  }

  dat.true = cbind(as.data.frame(X.train), y.train)
  dat.filled = cbind(as.data.frame(X.train.filled), y.train)
  dat.mvn = cbind(as.data.frame(X.train.filledMVN), y.train)

  lm.true = lm(y.train~., data = dat.true)
  lm.miss = lm(y.train~., data = dat.filled)
  lm.mvn  = lm(y.train~., data = dat.mvn)

  pred.true = predict(lm.true, X.test.filled.trueMean)
  pred.miss = predict(lm.miss, X.test.filled.missMean)
  pred.mvn = predict(lm.mvn, as.data.frame(X.test.filledMVN))

  err.true = mean((y.test-pred.true)^2)
  err.miss = mean((y.test-pred.miss)^2)
  err.mvn = mean((y.test-pred.mvn)^2)

  errs.true = c(errs.true,err.true)
  errs.miss = c(errs.miss,err.miss)
  errs.mvn = c(errs.mvn,err.mvn)
}

ggplot() +aes(x=miss.train.l) +
  geom_line(aes(y=errs.true, color='true')) + geom_line(aes(y=errs.miss, color='mean'))  + geom_line(aes(y=errs.mvn, color='mvn'))  +
  geom_vline(xintercept = miss_prop_test) + xlab('Missing data in train') + ylab('Error')

ggplot() + aes(x=miss.train.l, y=errs.mvn) + geom_line(color='green') + geom_vline(xintercept = miss_prop_test)
```

